const String supabaseUrl = 'https://txyjxeovxdeylekjxlat.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eWp4ZW92eGRleWxla2p4bGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxODM2MTYsImV4cCI6MjA4Nzc1OTYxNn0.OeX3ColMqIishwUovC0iv70CxHSEIreCky-h_EfnEqg';
